### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by dmcg89** [Jeromeschmidt/superheroTeamDueler#1]
- Although most tests passed, there was at least one per test file that did not
- Follow same logic in weapons class as you did with ability/armor classes (include __init__)
- Clean up unused code
- Overall great implementation with creative extra features!

**Comment by Jeromeschmidt** [comment]
Hey Drew, I agree some of the tests may need to be rewritten as adding additional features that included some randomness to them affected the already written tests. Thanks for the great feedback!
